### ISSUE TITLE
ES5 version?

### ISSUE THREAD

**Issue by ilsenem** [ZitRos/toaster-js#1]
Most build systems recommend to ignore `node_modules` from transpilation process, and your library fail to load with errors, since some of the features, like `import`, are not supported in browsers. 

For now, the only way to use it and not mess with working build configuration is to clone repository with library in project files, which is not so good for versioning and updates.

**Comment by nikitaeverywhere** [comment]
Hi @ilsenem!

If I were you, I would prefer rather setting up the rule ([like this](http://stackoverflow.com/a/39349302/2590150)) for your transpiler (I suppose you're using Babel with Browserify). ES6 is likely to get its native support soon, maybe in 1-2 years. I use [Webpack](https://webpack.github.io/) for bundling (always recommend it, as a former user of Browserify), and it handles ES6 modules very well.

The advantages of using ES6 modules over, say UMD are:
1. Support of tree-shaking;
2. Better linting (when you use such IDEs like IDEA, it is able to suggest all definitions, types and signatures of the library).
3. Saving space! (Because if you application use, for example, around 30 UMD-packed modules, you will notice that there is at least 10kb of redundant code in your bundle dedicated to detecting whether `modules.exports` (..., etc) is defined in your environment, for nothing).

If you still want to use the bundle, i will provide one:

```js
var Toast = require("toaster-js/umd.js");
```

Please let me know. Thank you!

**Comment by nikitaeverywhere** [comment]
Anyway, it is a good point to provide ES5 UMD version for whatever case people need.

**Comment by ilsenem** [comment]
I use [Brunch](http://brunch.io), and yes, i managed to provider rule for include your library into project with transpilation.

In any case, separate bundle would be great addition, thanks!

**Comment by nikitaeverywhere** [comment]
I've updated [the project](https://www.npmjs.com/package/toaster-js) with UMD module and also added [a demo](https://zitros.github.io/toaster-js/). Thanks for your notes!
